name: Asgn8
description: csc430 assignment 8
version: 1.0.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  http: ^1.4.0
  path: ^1.8.0
  test: ^1.26.2


# Optional: Add additional configurations like executables or dependency overrides
# executables:
#   my_executable: bin/my_executable.dart

# dependency_overrides:
#   some_package:
#     path: ../local_package_path
